github.com:
    users:
        Emilio20d2:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: Emilio20d2
